apiVersion: apps/v1
kind: Deployment
metadata:
  name: niyo-deployment
  labels:
    app: niyo-app
    type: front-end
spec:
  template:
    metadata:
      name: niyo-pod
      labels:
        app: niyo-app
    spec:
      containers:
        - name: niyo-deployment-container
          image: nginx
  replicas: 4
  selector:
    matchLabels:
      app: niyo-app
