apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod #pod name
  labels:
    name: result-app-pod #pod name
    app: demo-voting-app #app name

spec:
  containers:
    - name: result-app
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80
