apiVersion: v1
kind: Service
metadata:
  name: voting-service #Name used by other services to  call this service
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: result-app-pod #pod name
    app: demo-voting-app #app name
