apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-app-pod #pod name
      app: demo-voting-app #app name

  template:
    metadata:
      name: result-app-pod #pod name
      labels:
        name: result-app-pod #pod name
        app: demo-voting-app #app name

    spec:
      containers:
        - name: result-app
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80
